### ISSUE TITLE
Add break_or_goal and break_or

### ISSUE THREAD

**Issue by Kethku** [uwplse/StructTact#11]
I dont know if this is useful, but it might make it more consistent.

**Comment by wilcoxjay** [comment]
When you have a disjunction in the goal, you have a choice to make about which disjunct you're going to prove. What is the proposed behavior of `break_or_goal`? Would it just pick one of the disjuncts randomly?

**Comment by Kethku** [comment]
You could potentially have two versions, break left and break right to pick which side of the disjunct to pick. It might not be useful though, I was just looking for places where it could be more consistent.

**Comment by wilcoxjay** [comment]
There are built-in tactics `left` and `right` for that, so I think I will close this.

**Comment by Kethku** [comment]
perfect sounds good.
